r48102 の受け付けられないキーワード引数のエラー処理時にブロックが呼ばれてしまう
問題の再修正。エラー処理のほうを変更するのではなくて、rb_hash_delete() はブロッ
クの呼び出しをしないように変更しています。 [ruby-core:65861] [Bug #10413]
