Object#send で渡されたブロックを呼び出すメソッドにそのまま渡す処理を呼び出すメ
ソッドを見付ける作業の前にしてしまっていたため、そこで例外が発生すると例外オブ
ジェクトの生成中のメソッド(inspect とか)にそのブロックが渡されてしまっていた不
具合を修正。
