freeze されたオブジェクトに破壊的変更を行おうとした時に発生する例外を
RuntimeError からそれを継承した FrozenError という例外を発生させるようにしてい
ます。おお、例外クラスで判定できるようになるんですね。これは結構大きな変更です
ね。
