[ruby-dev:30653] の現象のためにテスト用のスクリプト test/ruby/lbtest.rb で生成
した Thread を待つ b.join をコメントアウトしたため、最後に "exit." というメッセ
ージを出した後に "n: done" というメッセージが出力することがありえるため、assert
で最後のメッセージが "exit." になることをチェックしていたのを削除しています。
